%Guick Guide
%1. Make sure that all simulations to be compared have the same velocities
%and acceleration settings
%2. Cofigure turn direction and KPI Index
%3. Add all directories wich include the output.mat file generated by the
%'create_YMD_album' script. The number of directories is unlimited
%4. Run

%% Configuration of Plot

kpi_idx=10; %index of requested kpi (see 'calculate_KPI' script for complete list of available KPI)
ax_idx=1; %index of the ax value to be plotted

%% generate plot

sz=size(kpi);

for v=1:length(v_range)
    values1(v,1:sz(5))=reshape(kpi(1,kpi_idx,v,ax_idx,:), [1,sz(5)]);
    values2(v,1:sz(5))=reshape(kpi(2,kpi_idx,v,ax_idx,:), [1,sz(5)]);
    values(v,1:(sz(5)*2))=abs([flip(values1(v,:),2), values2(v,:)]);
end
    banking1=-banking_range;
    banking2=banking_range;
    banking_all=[flip(banking1,2), banking2];
    
figure()
hold on
for v=1:length(v_range)
    plot(banking_all, values(v,:), 'DisplayName',strcat(num2str(v_range(v)),'mps'))
end
legend
xlabel('banking [deg]')
ylabel('lateral acceleration [m/s^{2}]')
grid on
title(['ay over banking @ a_x=', num2str(ax_range(ax_idx)), 'mps2'])
legend
