%Guick Guide
%1. Make sure that all simulations to be compared have the same velocities
%and acceleration settings
%2. Cofigure turn direction and KPI Index
%3. Add all directories wich include the output.mat file generated by the
%'create_YMD_album' script. The number of directories is unlimited
%4. Run

%% Configuration of Plot
clear

direction=1; %direction of turn 1==LH turn; 2== RH turn
kpi_index=1; %index of requested kpi (see 'calculate_KPI' script for complete list of available KPI)

dir(1)={'C:\...'};
dir(2)={'C:\...'};
dir(3)={'C:\...'};


%% Plot Gerneration
KPI_load

%assemble y vector of plot

inti_k=1;
for inti_k_v=1:max(size(v_range))
    for inti_k_a=1:max(size(ax_range))
        for inti_k_d=1:max(size(dir))
            kpi_bar(inti_k,inti_k_d)=kpi_dir(direction,kpi_index,inti_k_v,inti_k_a,inti_k_d);
            kpi_bar_descr(inti_k)=categorical({['v=' num2str(v_range(inti_k_v)) 'mps ax=' num2str(ax_range(inti_k_a)) 'mps2']});
        end
        inti_k=inti_k+1;
    end
end

bar(kpi_bar_descr,kpi_bar);
grid on
grid minor
title(kpi_descr(kpi_index))
ylabel(kpi_unit(kpi_index))
legend(dir_name, 'Interpreter', 'none','Location','northwest')